name: Fleet Manager Workflow
on:
  pull_request:
    branches: [ develop ]

jobs:
  web-deploy:
    name: Deploying
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install PHP packages
        run: |
          composer install --no-scripts

      - name: Create database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Copy env
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Clear config
        run: php artisan config:clear

      - name: Clear cache
        run: php artisan cache:clear

      - name: Setup Node 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          check-latest: false

      - name: Build project
        run:
          npm install
          npm run prod

      - name: Execute Test
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: vendor/bin/phpunit
